version: '3.8'

services:
  nice-components:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped
    container_name: nice-components
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nice-components.rule=Host(`nice-components.local`)"
      - "traefik.http.services.nice-components.loadbalancer.server.port=80"

  # 开发环境（可选）
  nice-components-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    container_name: nice-components-dev
    profiles:
      - dev 